### ISSUE TITLE
Rescheduling Events causes times to break 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2651]
Please see the video - Times are break when editing an event or saving the event 

https://www.loom.com/share/5ef767850daf4530a4abcf519d1de817

**Comment by Matchdev120** [comment]
@natalia-muzyka Just took a close look at the video.

The end time should be bigger than the start time but it's smaller than the start time, so the start time set to it when you clicked on the save button.

Actually, the original issue is resolved but I'm not sure if this is acceptable or what we expected.
Please review it once again and let me know.

**Comment by Matchdev120** [comment]
@natalia-muzyka Just took a close look at the video.

The end time should be bigger than the start time but it's smaller than the start time, so the start time set to it when you clicked on the save button.

Actually, the original issue is resolved but I'm not sure if this is acceptable or what we expected.
Please review it once again and let me know.

**Comment by WorldImpex** [comment]
@Matchdev120 Could we not allow the user to save ad show a warning? Is that easy?

**Comment by Matchdev120** [comment]
@WorldImpex  Yes, that's good and not difficult.

**Comment by natalia-muzyka** [comment]
@Matchdev120 after the latest changes warning is shown even when time is valid:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/b4c4d738-e1f7-46be-ae19-ad42918a7481)

Environment:
https://admin-staging.mindlogger.org/
v0.17.8
Win 10 / Chrome 102

**Comment by natalia-muzyka** [comment]
@Matchdev120 the issue from my last comment is still reproducible.
Warning is shown if minutes value in the end time is smaller than in the start time, although actually the time range is valid.
Video: https://www.screencast.com/t/xsURZE3aV6UA

**Comment by natalia-muzyka** [comment]
@Matchdev120 now it doesn't matter what I select, all the time is invalid.
Video: https://www.screencast.com/t/YyQBoVZc

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/2mKHFCMfV9

Environment:
https://admin-staging.mindlogger.org/
v0.17.11
Win 10 / Chrome 103
macOS BigSur 11.0 / Chrome 103
