### ISSUE TITLE
The "Hide badge" checkbox works in opposite way to its state

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-app#2792]
**Steps to reproduce**

1. Open a site and log in https://admin-staging.mindlogger.org/
2. Create a new applet with at least two activities or edit existing
3. Create a new flow(add name, description) and save
4. Log in to mobile app
5. Proceed to the applet screen
6. Pay attention to the flow that has unselected "Hide badge" checkbox in the builder

**Actual result**
The "Hide badge" checkbox works in the opposite way to its state: 
1. When on the applet builder side the checkbox is **disallowed** the badge is **hidden** on the mobile app. 
2. When on the applet builder side the checkbox is **allowed** the badge is **shown** on the flow card on the mobile app.

**Expected result**
The "Hide badge" checkbox works according to its state: 
1. When on the applet builder side the checkbox is **disallowed** the badge is **shown** on the mobile app. 
2. When on the applet builder side the checkbox is **allowed** the badge is **hidden** on the flow card on the mobile app.

Requirements (report components / Score component): https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features?node-id=2%3A3060

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/62eadcdc-7dc7-49eb-8482-b16a8266053b)

Requirements:
https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features?node-id=38%3A2946
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/30c5afdb-c2ec-4dba-a52e-47e6dafdbc4f)

**Environment:**
ML v0.21.38 staging
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11
user-stg@ml.com / 123456
config reports v9 / My Flow 1, My Flow 3
Applet password: Qwe123!!!

**Comment by MaksimYurys** [comment]
Verified as fixed.

Screenshots: ![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/60547bc8-a0ab-4f7f-b1ed-372a1ff49ef8)
![image.png](https://images.zenhubusercontent.com/62a1cc64855c1ef74c09c9d9/b52e268d-1165-4724-b363-9aefaea8b97b)

Environment:
https://admin-staging.mindlogger.org/
v0.17.14
Win 10 // Chrome 103
ML v0.21.42
iPhone 8 // iOS 14.7.1
Samsung Galaxy S8 // Android 8
JhoneeMind@gmail.com // Qqww!123
ConfReports 3 // Qqww!123

**Comment by iradchenk0** [comment]
@anq83 

![image.png](https://images.zenhubusercontent.com/631f33964819d323745f21b6/908e4011-9477-4ffd-bc06-98f0b2c10c84)

So, all issues on applet-builder are fixed (package version 0.18.51-alpha, till it's approved), but seems like the remaining issue is on mobile app side

**Comment by anq83** [comment]
@iradchenk0 
have you deployed it onto Stage ?

**Comment by anq83** [comment]
I've fixed it for mobile.
You can see it working correctly when:
1. Deploy applet-builder changes
2. Deploy mobile changes
3. Change the value in the flow and save it
4. Refresh the mobile app

If only to refresh mobile app without change checkbox in Admin - then backend will not return the actual value to mobile app.
And mobile app will not change it's checkbox state which is wrong.

**Comment by anq83** [comment]
That means - after deploy it into prod - real users will still see the bugfix until checkbox in admin changes and user refresh the app. 

If to change the flag twice in admin - it will help (initiates backend to return actual value)

**Comment by anq83** [comment]
@natalia-muzyka

**Comment by TatianaBessonova** [comment]
Verified as fixed. Appearance of a flow in the app corresponds to the state of the "Hide badge" checkbox:
1. When on the applet builder side the checkbox is disallowed the badge is shown on the mobile app.
2. When on the applet builder side the checkbox is allowed the badge is hidden on the flow card on the mobile app.
**Environment:**
https://admin-staging.mindlogger.org/
Applet builder version v0.18.5-alpha
iPhone 7 Plus / iOS 14.4
Google Pixel 3 XL / Android 1![4.png](https://images.zenhubusercontent.com/6343d78c6dec4b57073d9061/718e18ef-d6b8-40e5-b85e-4cfc9728edfe)0

**Comment by TatianaBessonova** [comment]
Verified on vmbile app version 0.21.57

**Comment by natalia-muzyka** [comment]
Verified as fixed.

Environment:
ML v0.21.57 staging
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11
